steps:         
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'storage', 'cp', '-R', 'gs://gemenielabs-stocks_cloudbuild/pytorch', '.' ]
     
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/stocks/myimage', '.' ]
   
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/stocks/myimage']
    
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'stocks-backend-sentiment', '--image', 
           'us-central1-docker.pkg.dev/$PROJECT_ID/stocks/myimage',
           '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated']   
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/stocks/myimage
  

      

